-- MySQL Script generated by MySQL Workbench
-- Sat Feb  5 13:57:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Banished
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Banished
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Banished` ;
USE `Banished` ;

-- -----------------------------------------------------
-- Table `Banished`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banished`.`workers` (
  `work_id` INT UNSIGNED NOT NULL,
  `work_desc` VARCHAR(45) NOT NULL,
  `work_total` INT NULL,
  `place_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`work_id`, `place_id`),
  UNIQUE INDEX `work_id_UNIQUE` (`work_id` ASC) VISIBLE,
  UNIQUE INDEX `work_type_UNIQUE` (`work_desc` ASC) VISIBLE,
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banished`.`places`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banished`.`places` (
  `place_id` INT UNSIGNED NOT NULL,
  `place_desc` VARCHAR(45) NOT NULL,
  `place_total` INT NULL,
  PRIMARY KEY (`place_id`),
  UNIQUE INDEX `place_id_UNIQUE` (`place_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banished`.`itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banished`.`itens` (
  `item_id` INT UNSIGNED NOT NULL,
  `item_desc` VARCHAR(45) NOT NULL,
  `item_total` INT UNSIGNED NULL,
  `places_place_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`item_id`, `places_place_id`),
  UNIQUE INDEX `item_id_UNIQUE` (`item_id` ASC) VISIBLE,
  INDEX `fk_itens_places1_idx` (`places_place_id` ASC) VISIBLE,
  CONSTRAINT `fk_itens_places1`
    FOREIGN KEY (`places_place_id`)
    REFERENCES `Banished`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banished`.`works_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banished`.`works_in` (
  `place_total` INT NULL,
  `places_place_id` INT UNSIGNED NOT NULL,
  `works_work_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`places_place_id`, `works_work_id`),
  INDEX `fk_works_in_places1_idx` (`places_place_id` ASC) VISIBLE,
  INDEX `fk_works_in_workers1_idx` (`works_work_id` ASC) VISIBLE,
  CONSTRAINT `fk_works_in_places1`
    FOREIGN KEY (`places_place_id`)
    REFERENCES `Banished`.`places` (`place_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_works_in_workers1`
    FOREIGN KEY (`works_work_id`)
    REFERENCES `Banished`.`workers` (`work_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Banished`.`works_with`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Banished`.`works_with` (
  `works_work_id` INT UNSIGNED NOT NULL,
  `itens_item_id` INT UNSIGNED NOT NULL,
  `itens_item_total` INT NULL,
  PRIMARY KEY (`works_work_id`, `itens_item_id`),
  INDEX `fk_workers_has_itens_itens1_idx` (`itens_item_id` ASC) VISIBLE,
  INDEX `fk_workers_has_itens_workers_idx` (`works_work_id` ASC) VISIBLE,
  CONSTRAINT `fk_workers_has_itens_workers`
    FOREIGN KEY (`works_work_id`)
    REFERENCES `Banished`.`workers` (`work_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_has_itens_itens1`
    FOREIGN KEY (`itens_item_id`)
    REFERENCES `Banished`.`itens` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
